name: robotframework-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - openiap-edge==0.0.28
    - robotframework==7.2.2
    - robotframework-selenium2library==3.0.0
    - selenium==4.31.0
